name: Publish Docker
on:
  push:
    branches: [ main ]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lorenzogl/ubademy-backoffice-web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}

  push-okteto-pipeline:
    needs: publish-docker-image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Create and populate kubernetes/frontend.yml file
      env:
        GIT_SHA_SECRET: ${{ github.sha }}
      run: |
        touch kubernetes/frontend.yml
        sed "s|GIT_SHA_SECRET|$GIT_SHA_SECRET|" kubernetes-templates/frontend.yml > kubernetes/frontend.yml
        echo "cat kubernetes/frontend.yml"
        cat kubernetes/frontend.yml

        echo "ls -a ."
        ls -a .

        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}
      shell: bash
    
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        namespace: lorenzolgz

    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: kubernetes
